#!/bin/sh

pkill stalonetray
stalonetray -c ~/.stalonetrayrc &

pkill xsettingsd
xsettingsd -c ~/.xsettingsd &

# Make sure my physical keyboard gets the memo
setxkbmap -option ctrl:nocaps

echo "Xft.dpi: 160" | xrdb -merge

# Restart xmobar
xmonad --restart
